# Generated by Django 4.1.3 on 2022-11-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_product_delete_porduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="images"),
        ),
    ]
